name: Fuzzing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  main2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Install avahi headers and utils
      run: sudo apt-get update && sudo apt-get install libavahi-client-dev avahi-daemon avahi-utils pulseaudio-utils
    - uses: r7kamura/rust-problem-matchers@v1
    - name: Install nightly
      run: |
        rustup install nightly
        rustup default nightly
    - name: Install cargo-fuzz
      run: cargo install cargo-fuzz
    - name: Build, run fuzz test
      run: cargo fuzz run main2 -- -max_total_time=60
